# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Dbfinder
                                 A QGIS plugin
 This plugin serch localization from Database and show localization in map
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-25
        copyright            : (C) 2020 by Mateusz Ciborowski
        email                : mateusz.cibor123@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load Dbfinder class from file Dbfinder.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Db_finder import Dbfinder
    return Dbfinder(iface)
